PORT: "3000"
RAILS_ENV: "development"
RAILS_MAX_THREADS: 5

API_KEY: "api_key_here"

# DEVISE
DEVISE_SECRET_KEY: "123"

# DATABASE CONNECTION
DATABASE_USERNAME: "user"
DATABASE_PASSWORD: "password"
DEV_DATABASE: "database"
