common: &common
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || "localhost" %>
  port: <%= ENV['DATABASE_PORT'] || "5432" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  gssencmode: "disable"

development: &development
  <<: *common
  database: <%= ENV['DEV_DATABASE'] %>

test:
  <<: *common
  database: neofit_api_test

production:
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
  prepared_statements: false
  advisory_locks: false
  statement_timeout: <%= ENV.fetch("RAILS_STATEMENT_TIMEOUT") { 5000 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
